/*
 * ======================================================================================
 * PROJECT: M5Console - MASTER (Final V7 - 8 Physical Buttons)
 * HARDWARE: M5Atom Lite
 * INPUTS: 8 Physical Buttons (GPIO 21, 25, 23, 33, 22, 19, 26, 32)
 * WEBAPP: 8 Buttons (Rectangular), 2 Columns
 * AUTHOR: Generated by AI Assistant guided by Mauricio Martins.
 * DATE: 2026-02-16
 *
 * CHANGELOG :
 * - Added support for all 8 physical GPIOs as originally requested.
 * - Mapped GPIOs 0-3 to Slave 1 and 4-7 to Slave 2.
 * ======================================================================================
 */

#include <WiFi.h>
#include <esp_now.h>
#include <WebServer.h>
#include <FastLED.h>

// --- LED CONFIGURATION (ATOM LITE) ---
#define LED_PIN     27
#define NUM_LEDS    1
#define LED_TYPE    WS2812
#define COLOR_ORDER GRB
#define BRIGHTNESS  255// 100%

CRGB leds[NUM_LEDS];

// --- MAC ADDRESSES ---
// Slave 1: Relays 1-4
uint8_t slave1Address[] = {0x00, 0x4B, 0x12, 0xA1, 0x94, 0xCC};

// Slave 2: Relays 5-8
uint8_t slave2Address[] = {0x90, 0x15, 0x06, 0xFA, 0x2C, 0x20};

// --- PINS & TIMERS ---
// Ordem: Btn1, Btn2, Btn3, Btn4, Btn5, Btn6, Btn7, Btn8
const int buttonPins[8] = {21, 25, 23, 33, 22, 19, 26, 32}; 

const unsigned long TIMEOUT_MS = 30000; 
const unsigned long DEBOUNCE_MS = 50;

// --- STRUCTURES ---
typedef struct struct_message {
  uint8_t relayId; // 0-3 (Relay index for the specific slave)
  bool state;
} struct_message;

struct_message myData;

struct ChannelState {
  bool isOn;
  unsigned long lastActiveTime;
  int pin; 
  int lastReading;
  unsigned long lastDebounceTime;
};

// Gerimos 8 canais no total
volatile ChannelState channels[8];
WebServer server(80);

// --- ESP-NOW SEND CALLBACK ---
void OnDataSent(const uint8_t *mac_addr, esp_now_send_status_t status) {
  if (status == ESP_NOW_SEND_SUCCESS) {
    fill_solid(leds, NUM_LEDS, CRGB::Green); // Success
  } else {
    fill_solid(leds, NUM_LEDS, CRGB::Red);   // Error
  }
  FastLED.show();
}

// --- SEND COMMAND ---
void sendCommand(uint8_t globalId, bool state) {
  uint8_t *targetMac;
  uint8_t localId;

  // Mapping Logic:
  // 0-3 -> Slave 1 (Left Column / GPIOs 21, 25, 23, 33)
  // 4-7 -> Slave 2 (Right Column / GPIOs 22, 19, 26, 32)
  if (globalId < 4) {
    targetMac = slave1Address;
    localId = globalId;
  } else {
    targetMac = slave2Address;
    localId = globalId - 4; // Map 4->0, 5->1, etc.
  }

  myData.relayId = localId;
  myData.state = state;
  
  esp_now_send(targetMac, (uint8_t *) &myData, sizeof(myData));
  
  if (state) {
    channels[globalId].lastActiveTime = millis();
  }
}

// --- WEB INTERFACE (HTML/CSS/JS) ---
const char index_html[] PROGMEM = R"rawliteral(
<!DOCTYPE HTML><html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>M5 Console</title>
  <style>
    body { 
      font-family: 'Segoe UI', sans-serif; 
      background: #000; 
      color: #fff; 
      margin: 0; 
      padding: 10px; 
      box-sizing: border-box;
    }
    
    /* Layout: 2 Columns Grid */
    .container {
      display: grid;
      grid-template-columns: 1fr 1fr; /* 50% - 50% */
      gap: 10px; 
      max-width: 600px;
      margin: 0 auto;
    }

    .column {
      display: flex;
      flex-direction: column;
      gap: 10px;
    }

    /* Rectangular Buttons (2:1 Ratio) */
    .btn {
      width: 100%;
      aspect-ratio: 2 / 1; /* Width is double the height */
      background-color: #222;
      border: 2px solid #444;
      color: #eee;
      font-size: 2rem;
      font-weight: bold;
      border-radius: 8px;
      cursor: pointer;
      -webkit-tap-highlight-color: transparent;
      user-select: none;
      touch-action: manipulation;
      transition: background 0.05s, transform 0.05s;
      
      /* Center text */
      display: flex; align-items: center; justify-content: center;
    }

    /* Active State (Green) */
    .btn:active, .btn.active {
      background-color: #00e600;
      color: black;
      border-color: #00e600;
      transform: scale(0.96);
    }
  </style>
</head>
<body>
  
  <div class="container">
    <!-- LEFT COLUMN: Buttons 1 to 4 (Slave 1) -->
    <div class="column">
      <div class="btn" id="b0">1</div>
      <div class="btn" id="b1">2</div>
      <div class="btn" id="b2">3</div>
      <div class="btn" id="b3">4</div>
    </div>

    <!-- RIGHT COLUMN: Buttons 5 to 8 (Slave 2) -->
    <div class="column">
      <div class="btn" id="b4">5</div>
      <div class="btn" id="b5">6</div>
      <div class="btn" id="b6">7</div>
      <div class="btn" id="b7">8</div>
    </div>
  </div>

  <script>
    function send(id, st) { 
      fetch((st ? '/on' : '/off') + '?id=' + id, {method: 'GET', keepalive: true}).catch(e=>{}); 
    }

    // Attach events to all 8 buttons
    for (let i = 0; i < 8; i++) {
      let btn = document.getElementById('b' + i);
      
      let press = (e) => { 
        if(e.cancelable) e.preventDefault(); 
        btn.classList.add('active'); 
        send(i, 1); 
      };

      let release = (e) => { 
        if(e.cancelable) e.preventDefault(); 
        btn.classList.remove('active'); 
        send(i, 0); 
      };

      // Touch events (Mobile)
      btn.addEventListener('touchstart', press, {passive: false});
      btn.addEventListener('touchend', release, {passive: false});
      btn.addEventListener('touchcancel', release, {passive: false});
      
      // Mouse events (Desktop)
      btn.addEventListener('mousedown', press);
      btn.addEventListener('mouseup', release);
      btn.addEventListener('mouseleave', release);
    }
  </script>
</body>
</html>
)rawliteral";

// --- WEB REQUEST HANDLER ---
void handleWebCommand(bool state) {
  if (server.hasArg("id")) {
    int id = server.arg("id").toInt();
    if (id >= 0 && id < 8) {
      channels[id].isOn = state;
      sendCommand(id, state);
      server.send(200, "text/plain", "");
    }
  } else {
    server.send(400, "text/plain", "Missing ID");
  }
}

// --- WEB SERVER TASK ---
void TaskWeb(void * pvParameters) {
  server.on("/", HTTP_GET, []() { server.send(200, "text/html", index_html); });
  
  server.on("/on", HTTP_GET, [](){ handleWebCommand(true); });
  server.on("/off", HTTP_GET, [](){ handleWebCommand(false); });

  server.begin();
  for(;;) { server.handleClient(); delay(2); }
}

// --- SETUP ---
void setup() {
  // 1. LED Setup
  FastLED.addLeds<LED_TYPE, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS);
  FastLED.setBrightness(BRIGHTNESS);
  fill_solid(leds, NUM_LEDS, CRGB::Red);
  FastLED.show();

  // 2. Button Setup (ALL 8 BUTTONS)
  for(int i=0; i<8; i++) {
    channels[i].isOn = false;
    channels[i].lastActiveTime = 0;
    
    // Configure all 8 pins (0 to 7)
    pinMode(buttonPins[i], INPUT); // Expecting External Pull-Up
    channels[i].pin = buttonPins[i];
    channels[i].lastReading = HIGH; // External Pull-Up: High = Released
  }

  // 3. WiFi Setup
  WiFi.mode(WIFI_AP_STA);
  WiFi.softAP("M5-Console", "12345678", 1, 0);

  // 4. ESP-NOW Setup
  if (esp_now_init() != ESP_OK) {
    while(1) { fill_solid(leds, 1, CRGB::White); FastLED.show(); delay(100); fill_solid(leds, 1, CRGB::Black); FastLED.show(); delay(100); }
  }
  esp_now_register_send_cb(OnDataSent);

  // Register Peers
  esp_now_peer_info_t peerInfo = {};
  peerInfo.channel = 1; peerInfo.encrypt = false;
  
  memcpy(peerInfo.peer_addr, slave1Address, 6);
  esp_now_add_peer(&peerInfo);

  memcpy(peerInfo.peer_addr, slave2Address, 6);
  esp_now_add_peer(&peerInfo);

  // 5. Start Tasks
  xTaskCreatePinnedToCore(TaskWeb, "TaskWeb", 6000, NULL, 1, NULL, 0);
}

// --- LOOP ---
void loop() {
  unsigned long currentMillis = millis();

  // 1. Read ALL 8 Physical Buttons
  for (int i = 0; i < 8; i++) {
    int reading = digitalRead(channels[i].pin);

    if (reading != channels[i].lastReading) {
      channels[i].lastDebounceTime = currentMillis;
    }

    if ((currentMillis - channels[i].lastDebounceTime) > DEBOUNCE_MS) {
      static int stableState[8] = {HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, HIGH};
      if (reading != stableState[i]) {
        stableState[i] = reading;
        // LOW = Pressed (External Pull-Up logic)
        if (stableState[i] == LOW) {
          channels[i].isOn = !channels[i].isOn; // Toggle
          sendCommand(i, channels[i].isOn);
        }
      }
    }
    channels[i].lastReading = reading;
  }

  // 2. Timeout Watchdog (For all 8 channels)
  for (int i = 0; i < 8; i++) {
    if (channels[i].isOn) {
      if (currentMillis - channels[i].lastActiveTime > TIMEOUT_MS) {
        channels[i].isOn = false;
        sendCommand(i, false);
      }
    }
  }

  delay(10);
}